DROP TABLE IF EXISTS records;

CREATE TABLE records
(
    id  SERIAL PRIMARY KEY,
    date  date NOT NULL,
    price_ars DOUBLE PRECISION NOT NULL,
    price_cad DOUBLE PRECISION NOT NULL,
    price_czk DOUBLE PRECISION NOT NULL,
    price_eur DOUBLE PRECISION NOT NULL,
    price_nok DOUBLE PRECISION NOT NULL,
    price_usd DOUBLE PRECISION NOT NULL
);
